--- 
title: "Impacto programas PAES y PEAMA"
author: "Daniel Rodriguez Chaves"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
documentclass: book
bibliography: [book.bib, packages.bib]
biblio-style: apalike
link-citations: yes
description: "Impacto de los programas de admisión especial (PAES y PEAMA) en términos de admisión, permanencia y graduación, en el marco de las políticas de inclusión educativa en la Universidad Nacional de Colombia."
---

# Introducción

Con el objetivo de analizar el impacto que han tenido los programas PAES y PEAMA con respecto a la admisión a la Universidad Nacional de Colombia de las poblaciones menos favorecidas de tal manera que exista equidad, además de medir el impacto de los programas de bienestar universitario sobre la permanencia y culminación de los procesos académicos de los estudiantes pertenecientes a los programas PAES y PEAMA se propusieron metodologías estadísticas que permiten llevar a cabo tales mediciones que se propuso como tarea en la Dirección Nacional de Bienestar Universitario. Es decir, determinar el impacto que han tenido los programas PAES y PEAMA con respecto a la admisión a la Universidad Nacional, en el marco de las políticas de inclusión educativa en la Universidad Nacional de Colombia

A continuación se precisa un poco a que se hace referencia con la medición de impacto.

## Evaluación de impacto

- Evalúa los efectos positivos o negativos, intencionados o no, generados por una actividad de desarrollo dada, como un programa o proyecto. Este tipo de evaluación alude tanto al impacto final (largo plazo) como a los efectos a nivel de resultado (mediano plazo).

- Además de medir si se han alcanzado los objetivos, evalúa los efectos directos en los beneficiarios a los que se dirige, engloba un abanico completo de impactos a todos los niveles de la cadena de resultados, incluido el efecto dominó (familias, hogares y comunidades).

- La evaluación del impacto determina en qué medida la iniciativa, más que cualquier otro factor externo, ha contribuido a los impactos que se han observado; es decir, hasta qué punto se alcanzaron los resultados previstos.

**Bibliografia de esta parte**


 _sample_ **Markdown** <https://yihui.name/tinytex/>.

